#!/bin/bash


if [[ $# > 0 ]]
then
    echo "Arguments are Invalid $0" >&2
else
    
    cd ~
    yourfilenames=`find -type f -not -name ".*" -printf '%P\n'`
    
    
    for eachfile in $yourfilenames
    do
        echo $eachfile >>./listOfFiles.list
    done
    
    if [[ -f ~/.census-data ]]
    then
        
        if ! [[ -w ~/.census-data ]]
        then
            echo "Can't write to ~/census-data" >&2
        else
            comm -2 -3 <(sort ~/.census-data) <(sort ./listOfFiles.list) >./tmpDel
            
            if [[ -s ./tmpDel ]]
            then
                echo "Deleted:"
                while read line
                do
                    echo "    "$line""
                done <./tmpDel
                
            fi
            if [[ -f ./tmpDel ]]
            then
                rm ./tmpDel
            fi
            comm -1 -3 <(sort ~/.census-data) <(sort ./listOfFiles.list) >./tmpNew
            if [[ -s ./tmpNew ]]
            then
                echo "New:"
                while read line
                do
                    echo "`ls -l "$line" 2>/dev/null`">>lsFormat
                done <./tmpNew
                column -t ./lsFormat >temp
                while read line
                do
                    echo "    $line"
                done <./temp
                rm temp lsFormat
            fi
            if [[ -f ./tmpNew ]]
            then
                rm ./tmpNew
            fi
        fi
    fi
    
    cp ./listOfFiles.list ~/.census-data
    rm ./listOfFiles.list
fi